import "./globals.css";
import { Inter } from "next/font/google";
import ClientLayout from "./clientLayout";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import type { Metadata } from "next";
import { Toaster } from "@/components/ui/sonner"
import Providers from "./providers";
import StoreProvider from "@/store/storeProvider";
import AuthInitializer from "@/context/AuthInitializer";
import { Loader } from "lucide-react";

const inter = Inter({ subsets: ["latin"] });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Bluelight",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <StoreProvider>
          <Providers>
            <AuthInitializer/>
              <ClientLayout>
                {children}
              </ClientLayout>
              <Toaster />
          </Providers>
        </StoreProvider>
      </body>
    </html>
  );
}
